import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;

//this class takes the txt file generated by FileRunner, and converts it
//into a gif that displays that results of the simulation
public class Video {

    String fileName;

    Video(String fileName) {
        //the video will end up with the same name as the file from FileRunner
        super();
        this.fileName = fileName.substring(0,fileName.length()-4) + ".gif";

    }

    public BufferedImage createImage(ArrayList<Double[]> positions) {

        BufferedImage img = new BufferedImage(1280, 720, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = img.createGraphics();
        g2.setBackground(Color.BLACK);
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);

        for (Double[] pos : positions) {

        }

        return img;



    }
}
